# Generated by Django 3.2 on 2024-06-10 13:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OtherOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('IsRequired', models.BooleanField(default=True)),
                ('Text', models.TextField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Survey',
            fields=[
                ('SurveyID', models.AutoField(primary_key=True, serialize=False)),
                ('Title', models.CharField(max_length=200)),
                ('Description', models.TextField(blank=True, max_length=500)),
                ('Is_released', models.BooleanField(blank=True)),
                ('Is_open', models.BooleanField(default=True)),
                ('Is_deleted', models.BooleanField(default=False)),
                ('PublishDate', models.DateTimeField(null=True)),
                ('Category', models.IntegerField(default=0)),
                ('TotalScore', models.IntegerField(blank=True, null=True)),
                ('TimeLimit', models.IntegerField(blank=True, null=True)),
                ('IsOrder', models.BooleanField(default=True)),
                ('QuotaLimit', models.IntegerField(default=False, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Template',
            fields=[
                ('TemplateID', models.AutoField(primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=200)),
                ('Type', models.CharField(max_length=50)),
                ('DefaultQuestionsJSON', models.JSONField()),
                ('Description', models.TextField(blank=True, max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('UserID', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=50, unique=True)),
                ('password', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=100, unique=True)),
                ('CreateDate', models.DateTimeField(auto_now_add=True)),
                ('isActive', models.BooleanField(default=False)),
                ('zhibi', models.IntegerField(default=0)),
                ('own_photos', models.TextField(default='[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]')),
            ],
        ),
        migrations.CreateModel(
            name='UserRewardRecord',
            fields=[
                ('RecordID', models.AutoField(primary_key=True, serialize=False)),
                ('Zhibi', models.IntegerField()),
                ('RedemptionDate', models.DateField()),
                ('Respondent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reward_records', to='user.user')),
                ('Survey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_rewards', to='user.survey')),
            ],
        ),
        migrations.CreateModel(
            name='SurveyStatistic',
            fields=[
                ('StatisticID', models.AutoField(primary_key=True, serialize=False)),
                ('TotalResponses', models.IntegerField(default=0)),
                ('AverageScore', models.FloatField(blank=True, null=True)),
                ('LastResponseDate', models.DateTimeField(blank=True, null=True)),
                ('Survey', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='statistics', to='user.survey')),
            ],
        ),
        migrations.AddField(
            model_name='survey',
            name='Owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='surveys', to='user.user'),
        ),
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('SubmissionID', models.AutoField(primary_key=True, serialize=False)),
                ('SubmissionTime', models.DateTimeField(auto_now_add=True)),
                ('Status', models.CharField(choices=[('Unsubmitted', 'Unsubmitted'), ('Submitted', 'Submitted'), ('Graded', 'Graded'), ('Deleted', 'Deleted')], max_length=20)),
                ('Score', models.IntegerField(blank=True, null=True)),
                ('Interval', models.IntegerField(blank=True, null=True)),
                ('Respondent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='user.user')),
                ('Survey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='user.survey')),
            ],
        ),
        migrations.CreateModel(
            name='RewardOffering',
            fields=[
                ('RewardID', models.AutoField(primary_key=True, serialize=False)),
                ('Description', models.TextField()),
                ('Zhibi', models.IntegerField()),
                ('AvailableQuota', models.IntegerField()),
                ('Survey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rewards', to='user.survey')),
            ],
        ),
        migrations.CreateModel(
            name='RatingQuestion',
            fields=[
                ('QuestionID', models.AutoField(primary_key=True, serialize=False)),
                ('Text', models.TextField(max_length=500)),
                ('IsRequired', models.BooleanField(default=True)),
                ('QuestionNumber', models.IntegerField(default=0)),
                ('Score', models.IntegerField(blank=True, default=0, null=True)),
                ('Category', models.IntegerField()),
                ('MinRating', models.IntegerField(default=1, null=True)),
                ('MinText', models.TextField(max_length=500, null=True)),
                ('MaxRating', models.IntegerField(default=5, null=True)),
                ('MaxText', models.TextField(max_length=500, null=True)),
                ('Survey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratingquestion_questions', to='user.survey')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='RatingAnswer',
            fields=[
                ('AnswerID', models.AutoField(primary_key=True, serialize=False)),
                ('Rate', models.IntegerField(blank=True, null=True)),
                ('Question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.ratingquestion')),
                ('Submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratinganswer_answers', to='user.submission')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ChoiceQuestion',
            fields=[
                ('QuestionID', models.AutoField(primary_key=True, serialize=False)),
                ('Text', models.TextField(max_length=500)),
                ('IsRequired', models.BooleanField(default=True)),
                ('QuestionNumber', models.IntegerField(default=0)),
                ('Score', models.IntegerField(blank=True, default=0, null=True)),
                ('Category', models.IntegerField()),
                ('MaxSelectable', models.IntegerField(default=1, null=True)),
                ('OptionCnt', models.IntegerField(default=0)),
                ('Survey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='choicequestion_questions', to='user.survey')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ChoiceOption',
            fields=[
                ('OptionID', models.AutoField(primary_key=True, serialize=False)),
                ('Text', models.CharField(max_length=200)),
                ('IsCorrect', models.BooleanField(default=False, null=True)),
                ('OptionNumber', models.IntegerField(default=0)),
                ('Question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='choice_options', to='user.choicequestion')),
            ],
        ),
        migrations.CreateModel(
            name='ChoiceAnswer',
            fields=[
                ('AnswerID', models.AutoField(primary_key=True, serialize=False)),
                ('ChoiceOptions', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.choiceoption')),
                ('Question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.choicequestion')),
                ('Submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='choiceanswer_answers', to='user.submission')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='BlankQuestion',
            fields=[
                ('QuestionID', models.AutoField(primary_key=True, serialize=False)),
                ('Text', models.TextField(max_length=500)),
                ('IsRequired', models.BooleanField(default=True)),
                ('QuestionNumber', models.IntegerField(default=0)),
                ('Score', models.IntegerField(blank=True, default=0, null=True)),
                ('Category', models.IntegerField()),
                ('CorrectAnswer', models.TextField(max_length=100, null=True)),
                ('Survey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blankquestion_questions', to='user.survey')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='BlankAnswer',
            fields=[
                ('AnswerID', models.AutoField(primary_key=True, serialize=False)),
                ('Content', models.TextField(max_length=500)),
                ('Question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.blankquestion')),
                ('Submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blankanswer_answers', to='user.submission')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
