# Generated by Django 3.2 on 2024-08-16 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='survey',
            name='QuotaLimit',
        ),
        migrations.AddField(
            model_name='choiceoption',
            name='MaxSelectablePeople',
            field=models.IntegerField(default=-1),
        ),
    ]
